baseURL = 'https://pine64.org/'
languageCode = 'en-us'
title = 'PINE64'
theme = "pinetheme"

# Blog post summary limit
summaryLength = 30

# Stylistic options
pluralizelisttitles = "false"
disablePathToLower = true

# Syntax highlighting in fenced code
pygmentsCodeFences = true

# Table of contents
tableOfContents = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Pagination for the blog posts (x posts per page)
[pagination]
  disableAliases = false
  pagerSize = 9
  path = 'page'


# https://gohugo.io/getting-started/configuration-markup/
[markup]
  #[markup.asciidocExt]
  #  [markup.asciidocExt.attributes]
  #    sectlinks = true
  #    idprefix = ''
  #    allow-uri-read = ""
  #    icons = "font"
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'pastie'
    tabWidth = 4

[permalinks]
  blog = '/:year/:month/:day/:contentbasename/'

[cover]
  hidden = false # hide everywhere but not in structured data
  hiddenInList = false # hide on list pages and home
  hiddenInSingle = false # hide on single page

[params]
  images = ['/img/opengraph_main.png']
  [params.social]
    twitter = 'thepine64'

#[security.exec]
#  allow = ["^asciidoctor$"]

# Allow HTML inside markdown (e. g. for br in tables)
[markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true 

# Docs menu
[menu]
  [[menu.right]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 1
  [[menu.right]]
    name = "Community"
    pageRef = "/community/"
    weight = 2
  [[menu.right]]
    name = "Devices"
    pageRef = "/devices/"
    weight = 3
  [[menu.right]]
    name = "Documentation"
    pageRef = "/documentation/"
    weight = 4
  [[menu.right]]
    name = "Contests"
    pageRef = "/contests/"
    weight = 5
  [[menu.right]]
    name = "Podcast"
    pageRef = "/podcast/"
    weight = 6

  [[menu.additional]]
    name = "Store"
    post = "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='18' fill='none' stroke='#000' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='m6 9 6 6 6-6'/></svg>"
    pageRef = "#"
    weight = 0
    identifier = "store"
    [menu.additional.params]
      external = false
  [[menu.additional]]
    name = "🌐 Global"
    url = "https://www.pine64.com/"
    parent = "store"
    weight = 1
    identifier = ""
    [menu.additional.params]
      external = true
  [[menu.additional]]
    name = "🇪🇺 EU"
    url = "https://www.pine64eu.com/"
    parent = "store"
    weight = 2
    identifier = ""
    [menu.additional.params]
      external = true
  [[menu.additional]]
    name = "Affiliates"
    pageRef = "/affiliates"
    parent = "store"
    weight = 3
    identifier = ""
    [menu.additional.params]
      external = false