site_url: https://pine64.org
#publish_mode: editorial_workflow

#backend:
#  name: github
#  repo: pine64/website
#  branch: main

# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: pine64/website
  branch: main
  identity_url: https://auth.decapbridge.com/sites/724d1e08-c073-4673-93ef-1d9bc541bbda
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} (via CMS)
    update: Update {{collection}} “{{slug}}” - {{author-name}} (via CMS)
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} (via CMS)
    uploadMedia: Upload “{{path}}” - {{author-name}} (via CMS)
    deleteMedia: Delete “{{path}}” - {{author-name}} (via CMS)
    openAuthoring: Message {{message}} - {{author-name}} (via CMS)

media_folder: "static/images/uploads" # Adjust based on your media storage location
public_folder: "/images/uploads" # URL path for accessing media
logo: 
  src: https://pine64.org/img/logo.png
  show_in_header: true
search: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "blog" # This is the name used in the URL
    label: "Blog" # This is the singular name of the content type for the UI
    label_singular: "Blog post"
    folder: "content/blog" # The folder where your posts markdown files will be saved
    create: true # Allows users to create new documents in this collection
    slug: "{{slug}}" # Filename template for new posts
    preview_path: "{{year}}/{{month}}/{{day}}/{{slug}}/"
    preview: false
    delete: false
    fields: # List of fields for the front matter
      - { label: "Title", name: "title", widget: "string" }
      #- { label: "Description", name: "description", widget: "text", required: false}
      - { label: "Date", name: "date", widget: "datetime" }
      - name: authors
        label: Authors
        label_singular: 'Author'
        widget: list
        fields:
          - { label: 'Name', name: 'name', widget: 'string', hint: 'Name of the author' }
          #- { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: "Image", name: "images", widget: "image", required: false }
      #- { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      #- { label: "Comments", name: "comments", widget: "boolean", default: true }
      #- { label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      #- { label: "Weight", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "community" # This is the name used in the URL
    label: "Community" # This is the singular name of the content type for the UI
    label_singular: "Community"
    folder: "content/community" # The folder where your posts markdown files will be saved
    create: true # Allows users to create new documents in this collection
    slug: "{{slug}}" # Filename template for new posts
    preview: false
    delete: false
    fields: # List of fields for the front matter
      - { label: "Title", name: "title", widget: "string" }
      #- { label: "Description", name: "description", widget: "text", required: false }
      #- { label: "Date", name: "date", widget: "datetime", required: false }
      #- { label: "Image", name: "images", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "contests" # This is the name used in the URL
    label: "Contests" # This is the singular name of the content type for the UI
    label_singular: "Contest"
    folder: "content/contests" # The folder where your posts markdown files will be saved
    create: true # Allows users to create new documents in this collection
    slug: "{{slug}}" # Filename template for new posts
    preview: false
    fields: # List of fields for the front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false  }
      - { label: "Date", name: "date", widget: "datetime", required: false  }
      - { label: "Image", name: "images", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false  }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "devices" # This is the name used in the URL
    label: "Devices" # This is the singular name of the content type for the UI
    label_singular: "Device"
    folder: "content/devices" # The folder where your posts markdown files will be saved
    create: true # Allows users to create new documents in this collection
    slug: "{{slug}}" # Filename template for new posts
    preview: false
    delete: false
    fields: # List of fields for the front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false  }
      #- { label: "Date", name: "date", widget: "datetime", required: false  }
      - { label: "Image", name: "images", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false  }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "documentation" # This is the name used in the URL
    label: "Documentation" # This is the singular name of the content type for the UI
    label_singular: "Documentation"
    folder: "content/documentation" # The folder where your posts markdown files will be saved
    create: true # Allows users to create new documents in this collection
    preview: false
    delete: false
    nested:
      #subfolders: true # Legacy behavior
      subfolders: false
      depth: 15 # max depth to show in the collection tree
      summary: '{{dirname}}' # optional summary for a tree node, defaults to the inferred title field
    fields: # List of fields for the front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: 'Menu', name: 'menu', widget: 'object', required: false, collapsed: true,
          fields: [
            {
              label: 'docs', name: 'docs', widget: 'object', required: false, collapsed: true,
              fields: [
                { label: 'Title', name: 'title', widget: 'string' },
                { label: 'Parent', name: 'parent', widget: 'string' },
                { label: 'Identifier', name: 'identifier', widget: 'string' },
                { label: 'Weight', name: 'weight', widget: 'string' }
              ]
            }
          ]
        }
      #- {
      #    name: "aliases",
      #    label: "Aliases",
      #    required: false,
      #    widget: "list",
      #    allow_add: true,
      #    collapsed: true,
      #    minimize_collapsed: true
      #}
      - { label: "Body", name: "body", widget: "markdown" }

    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }

  - name: "podcast" # This is the name used in the URL
    label: "Podcast" # This is the singular name of the content type for the UI
    label_singular: "Podcast"
    folder: "content/podcast" # The folder where your posts markdown files will be saved
    create: true # Allows users to create new documents in this collection
    slug: "{{slug}}" # Filename template for new posts
    preview: false
    delete: false
    fields: # List of fields for the front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false  }
      - { label: "Date", name: "date", widget: "datetime", required: false  }
      - { label: "Image", name: "images", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false  }
      - { label: "Body", name: "body", widget: "markdown" }
